# Site settings
name: Wiki's Blog
email: tianyuanchun94@live.com
author: Yuanchun Tian
#url: http://www.hifreud.com
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/yuanchuntian/
baseurl: ""
description: Talk is cheap. Show me the code.
meta_description: Wiki;Blog;
motto: Talk is cheap. Show me the code.
banner: All those moments will be lost in time,like tears in rain. 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yuanchuantian

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

